version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "airway-shipment"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hihkcmymsrl1"
s3_prefix = "airway-shipment"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ShipmentRecordQueueName=\"ShipmentRecordQueue\" ShipmentRecordManualResubmitQueueName=\"ShipmentRecordManualResubmitQueue\" ShipmentRecordDLQueueName=\"ShipmentRecordDLQueue\" ShipmentRecordTableName=\"ShipmentRecord\" ShipmentHashTableName=\"ShipmentHash\""
image_repositories = []
